[project]
name = "vitruvian"
version = "0.1.0"
description = "Minimum viable humanoid as a substrate for machine intelligence."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "noahsabaj", email = "noahsabaj@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "brax>=0.14.2",
    "imageio>=2.37.3",
    "jax[cuda12]>=0.10.0",
    "mujoco>=3.7.0",
    "mujoco-mjx>=3.7.0",
    "mujoco-warp>=3.7.0.1",
    "playground>=0.2.0",
    "warp-lang>=1.12.1",
]

[project.scripts]
vitruvian = "vitruvian:main"

[build-system]
requires = ["uv_build>=0.8.0,<0.9"]
build-backend = "uv_build"

[tool.pyright]
venvPath = "."
venv = ".venv"

